name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
      # Install rye with cache
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
      # Sync dependencies
      - name: Sync dependencies
        run: rye sync
      # Run tests
      - name: Run tests
        run: rye test
      # Code coverage to codecov.io
#      - uses: codecov/codecov-action@v4
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: tests/coverage.xml
#          fail_ci_if_error: false
#          verbose: true 

  # Publishes to PyPi if tests are passed and release is created
#  publish:
#    if: github.event_name == 'release' && github.event.action == 'created'
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#      # Checkout repo
#      - name: Checkout
#        uses: actions/checkout@v3
#      # Install rye with cache
#      - name: Install the latest version of rye
#        uses: eifinger/setup-rye@v4
#        with:
#          enable-cache: true
#      # Sync dependencies
#      - name: Sync dependencies
#        run: rye sync
#      # Build and publish to PyPI
#      - name: Build and publish to pypi
#        uses: JRubics/poetry-publish@v1.17
#        with:
#          pypi_token: ${{ secrets.PYPI_TOKEN }}
#